//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.03 at 12:49:44 AM CEST 
//


package model.amandman;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/skupstina}DatumPredlaganja"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/skupstina}BrojClanova" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="vocab" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datumPredlaganja",
    "brojClanova"
})
@XmlRootElement(name = "MetaPodaci")
public class MetaPodaci {

    @XmlElement(name = "DatumPredlaganja", required = true)
    protected DatumPredlaganja datumPredlaganja;
    @XmlElement(name = "BrojClanova")
    protected BrojClanova brojClanova;
    @XmlAttribute(name = "vocab")
    protected String vocab;
    @XmlAttribute(name = "about")
    protected String about;
    @XmlAttribute(name = "rel")
    protected String rel;
    @XmlAttribute(name = "href")
    protected String href;

    /**
     * Gets the value of the datumPredlaganja property.
     * 
     * @return
     *     possible object is
     *     {@link DatumPredlaganja }
     *     
     */
    public DatumPredlaganja getDatumPredlaganja() {
        return datumPredlaganja;
    }

    /**
     * Sets the value of the datumPredlaganja property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatumPredlaganja }
     *     
     */
    public void setDatumPredlaganja(DatumPredlaganja value) {
        this.datumPredlaganja = value;
    }

    /**
     * Gets the value of the brojClanova property.
     * 
     * @return
     *     possible object is
     *     {@link BrojClanova }
     *     
     */
    public BrojClanova getBrojClanova() {
        return brojClanova;
    }

    /**
     * Sets the value of the brojClanova property.
     * 
     * @param value
     *     allowed object is
     *     {@link BrojClanova }
     *     
     */
    public void setBrojClanova(BrojClanova value) {
        this.brojClanova = value;
    }

    /**
     * Gets the value of the vocab property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVocab() {
        return vocab;
    }

    /**
     * Sets the value of the vocab property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVocab(String value) {
        this.vocab = value;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets the value of the rel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRel() {
        return rel;
    }

    /**
     * Sets the value of the rel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRel(String value) {
        this.rel = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHref(String value) {
        this.href = value;
    }

}
